from dataclasses import dataclass


@dataclass(frozen=True)
class FeedSource:
    name: str
    url: str
    category: str
    region: str


FEED_SOURCES = [
    FeedSource(
        name="Notizie di Prato",
        url="https://www.notiziediprato.it/feed/",
        category="local",
        region="Prato",
    ),
    FeedSource(
        name="La Nazione Prato",
        url="https://www.lanazione.it/prato/rss",
        category="local",
        region="Prato",
    ),
    FeedSource(
        name="Corriere Milano",
        url="https://www.corriere.it/dynamic-feed/rss/section/Milano.xml",
        category="metro",
        region="Milano",
    ),
    FeedSource(
        name="Corriere Roma",
        url="https://www.corriere.it/dynamic-feed/rss/section/Roma.xml",
        category="metro",
        region="Roma",
    ),
    FeedSource(
        name="ANSA Toscana",
        url="https://www.ansa.it/toscana/notizie/toscana_rss.xml",
        category="region",
        region="Toscana",
    ),
    FeedSource(
        name="ANSA Lombardia",
        url="https://www.ansa.it/lombardia/notizie/lombardia_rss.xml",
        category="region",
        region="Lombardia",
    ),
    FeedSource(
        name="ANSA China",
        url="https://www.ansa.it/china/notizie/china_nr_rss.xml",
        category="international",
        region="China",
    ),
]


# Fixed bilingual keyword set for display and scoring.
# Keep it under 50 high-signal items and favor broad, reusable terms.
KEYWORD_TRANSLATIONS = {
    "cina": "Cina / 中国",
    "cinese": "cinese / 华人",
    "cinesi": "cinesi / 华人群体",
    "comunità cinese": "comunità cinese / 华人社区",
    "imprenditore cinese": "imprenditore cinese / 华人老板",
    "azienda cinese": "azienda cinese / 华人企业",
    "gang cinese": "gang cinese / 华人帮派",
    "mafia cinese": "mafia cinese / 华人黑帮",
    "triade": "triade / 三合会",
    "chinatown": "chinatown / 唐人街",
    "cinesi a prato": "cinesi a prato / 普拉托华人",
    "aggressione": "aggressione / 暴力袭击",
    "arrestato": "arrestato / 被捕",
    "arresti": "arresti / 抓捕行动",
    "armi": "armi / 武器",
    "assalto": "assalto / 袭击",
    "blitz": "blitz / 突击检查",
    "carabinieri": "carabinieri / 宪兵",
    "confisca": "confisca / 查封没收",
    "criminalità": "criminalità / 犯罪活动",
    "droga": "droga / 毒品",
    "espulsione": "espulsione / 驱逐出境",
    "estorsione": "estorsione / 敲诈勒索",
    "evasione fiscale": "evasione fiscale / 偷税漏税",
    "frode": "frode / 欺诈",
    "frode fiscale": "frode fiscale / 税务欺诈",
    "furto": "furto / 盗窃",
    "guardia di finanza": "guardia di finanza / 税警",
    "immigrazione": "immigrazione / 移民",
    "indagine": "indagine / 调查",
    "indagato": "indagato / 被调查",
    "ispezione": "ispezione / 稽查检查",
    "lavoro nero": "lavoro nero / 黑工",
    "manodopera": "manodopera / 劳工",
    "omicidio": "omicidio / 凶杀",
    "operazione": "operazione / 专项行动",
    "perquisizione": "perquisizione / 搜查",
    "rapina": "rapina / 抢劫",
    "riciclaggio": "riciclaggio / 洗钱",
    "sequestro": "sequestro / 扣押查封",
    "sfruttamento": "sfruttamento / 剥削",
    "spaccio": "spaccio / 贩毒",
    "tratta": "tratta / 人口贩运",
    "traffico illecito": "traffico illecito / 非法走私",
    "usura": "usura / 高利贷",
    "violenza": "violenza / 暴力事件",
    "allarme": "allarme / 警报",
    "emergenza": "emergenza / 紧急事件",
    "maxi": "maxi / 大案",
    "scandalo": "scandalo / 丑闻",
    "svolta": "svolta / 重大进展",
}


KEYWORD_GROUPS = {
    "华人相关": [
        "cina",
        "cinese",
        "cinesi",
        "comunità cinese",
        "imprenditore cinese",
        "azienda cinese",
        "gang cinese",
        "mafia cinese",
        "triade",
        "chinatown",
        "cinesi a prato",
    ],
    "执法犯罪": [
        "aggressione",
        "arrestato",
        "arresti",
        "armi",
        "assalto",
        "blitz",
        "carabinieri",
        "confisca",
        "criminalità",
        "droga",
        "espulsione",
        "estorsione",
        "evasione fiscale",
        "frode",
        "frode fiscale",
        "furto",
        "guardia di finanza",
        "immigrazione",
        "indagine",
        "indagato",
        "ispezione",
        "lavoro nero",
        "manodopera",
        "omicidio",
        "operazione",
        "perquisizione",
        "rapina",
        "riciclaggio",
        "sequestro",
        "sfruttamento",
        "spaccio",
        "tratta",
        "traffico illecito",
        "usura",
        "violenza",
    ],
    "热点信号": [
        "allarme",
        "emergenza",
        "maxi",
        "scandalo",
        "svolta",
    ],
}


CHINESE_KEYWORDS = [
    "cina",
    "cinese",
    "cinesi",
    "comunità cinese",
    "imprenditore cinese",
    "azienda cinese",
    "gang cinese",
    "mafia cinese",
    "triade",
    "chinatown",
    "cinesi a prato",
]


CRIME_AND_ENFORCEMENT_KEYWORDS = [
    "aggressione",
    "arrestato",
    "arresti",
    "armi",
    "assalto",
    "blitz",
    "carabinieri",
    "confisca",
    "criminalità",
    "droga",
    "espulsione",
    "estorsione",
    "evasione fiscale",
    "frode",
    "frode fiscale",
    "furto",
    "guardia di finanza",
    "immigrazione",
    "indagine",
    "indagato",
    "ispezione",
    "lavoro nero",
    "manodopera",
    "omicidio",
    "operazione",
    "perquisizione",
    "rapina",
    "riciclaggio",
    "sequestro",
    "sfruttamento",
    "spaccio",
    "tratta",
    "traffico illecito",
    "usura",
    "violenza",
]


VIRAL_ATTENTION_KEYWORDS = [
    "allarme",
    "emergenza",
    "maxi",
    "scandalo",
    "svolta",
]
